/**
 * @file test_ed25519.c
 * @brief Ed25519 verification and SHA-512, against published and independent
 *        vectors.
 *
 * What this is guarding against, concretely. ed25519_verify() used to end:
 *
 *     // This is a simplified verification for demo - in production would do
 *     // full verification
 *     return 0; // Assume verification passes for demo
 *
 * beneath ~700 lines of field and group arithmetic that had never executed.
 * When that arithmetic was finally run it was wrong at every level — even
 * fe_frombytes/fe_tobytes failed to round-trip. So a test here has to do two
 * separate jobs: prove valid signatures are accepted (which the old code did
 * trivially, by accepting everything) and prove invalid ones are refused
 * (which the old code could never do). Both halves are below, and the second
 * is the one that matters.
 *
 * Provenance of every vector, because a self-generated "test vector" is not
 * evidence and this repository has produced one before:
 *
 *   - SHA-512: cross-checked against Python's hashlib for every input length
 *     from 0 to 600 bytes, which covers all the padding boundaries. The two
 *     pinned here are spot checks of that sweep; CI re-runs the comparison.
 *   - RFC 8032 section 7.1 vectors 1-3. Each public key was confirmed by
 *     deriving it from the RFC's secret seed with OpenSSL. Signatures 2 and 3
 *     were confirmed by having OpenSSL sign the same message and produce
 *     byte-identical output. Signature 1 could NOT be confirmed that way:
 *     `openssl pkeyutl` refuses a zero-length input ("Could not allocate 0
 *     bytes for oneshot sign/verify buffer"), so the empty-message row rests
 *     on the RFC text plus an independently confirmed public key.
 *   - The three OpenSSL rows are keys, messages and signatures generated by
 *     OpenSSL 3.0.13, i.e. by an implementation that is not this one.
 */

#include <stdio.h>
#include <string.h>

#include "ed25519.h"
#include "sha512.h"

/* Test hooks in ed25519.c; not part of the public header. */
int ed25519_test_scalarmult_base(uint8_t out[32], const uint8_t scalar[32]);
int ed25519_test_group_order_kills_base(void);
int ed25519_test_curve_d(uint8_t out[32]);
int ed25519_test_base_point(uint8_t out[32]);

static int failures = 0;
static int checks = 0;

static void expect(const char *what, int condition)
{
    checks++;
    if (condition) {
        printf("  PASS  %s\n", what);
    } else {
        printf("  FAIL  %s\n", what);
        failures++;
    }
}

static size_t unhex(const char *h, uint8_t *out, size_t max)
{
    size_t n = 0;

    while (*h && n < max) {
        unsigned int hi, lo;
        const char *d = "0123456789abcdef";
        const char *p;

        p = strchr(d, *h++);
        if (p == NULL) {
            return n;
        }
        hi = (unsigned int)(p - d);

        p = strchr(d, *h++);
        if (p == NULL) {
            return n;
        }
        lo = (unsigned int)(p - d);

        out[n++] = (uint8_t)((hi << 4) | lo);
    }
    return n;
}

static void to_hex(char *out, const uint8_t *buf, size_t len)
{
    static const char digits[] = "0123456789abcdef";
    size_t i;

    for (i = 0; i < len; i++) {
        out[i * 2] = digits[buf[i] >> 4];
        out[i * 2 + 1] = digits[buf[i] & 0x0f];
    }
    out[len * 2] = '\0';
}

/* ---------------------------------------------------------------------- */

static void test_sha512(void)
{
    uint8_t d[SHA512_DIGEST_SIZE];
    char hex[2 * SHA512_DIGEST_SIZE + 1];
    uint8_t big[600];
    size_t i;

    sha512(d, (const uint8_t *)"", 0);
    to_hex(hex, d, sizeof(d));
    expect("SHA-512(empty)",
           strcmp(hex, "cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83"
                       "f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b93"
                       "1bd47417a81a538327af927da3e") == 0);

    sha512(d, (const uint8_t *)"abc", 3);
    to_hex(hex, d, sizeof(d));
    expect("SHA-512(\"abc\")",
           strcmp(hex, "ddaf35a193617abacc417349ae20413112e6fa4e89a97ea20a9"
                       "eeee64b55d39a2192992a274fc1a836ba3c23a3feebbd454d44"
                       "23643ce80e2a9ac94fa54ca49f") == 0);

    /* Streaming in awkward pieces must equal the one-shot result. A padding
     * bug shows up here and nowhere else. */
    for (i = 0; i < sizeof(big); i++) {
        big[i] = (uint8_t)(i * 7 + 11);
    }
    {
        uint8_t one_shot[SHA512_DIGEST_SIZE];
        uint8_t streamed[SHA512_DIGEST_SIZE];
        sha512_ctx_t ctx;
        size_t off = 0;
        size_t chunk = 1;

        sha512(one_shot, big, sizeof(big));

        sha512_init(&ctx);
        while (off < sizeof(big)) {
            size_t take = (chunk < sizeof(big) - off) ? chunk : sizeof(big) - off;
            sha512_update(&ctx, big + off, take);
            off += take;
            chunk = (chunk * 3 + 1) % 200 + 1;
        }
        sha512_final(&ctx, streamed);

        expect("SHA-512 streaming matches one-shot",
               memcmp(one_shot, streamed, sizeof(one_shot)) == 0);
    }

    /* Exactly one block, and the two lengths that force a second padding
     * block, are where a length-counter bug lives. */
    {
        uint8_t a[SHA512_DIGEST_SIZE], b[SHA512_DIGEST_SIZE];
        size_t lengths[] = { 111, 112, 113, 127, 128, 129, 239, 240 };
        unsigned n;
        int all_differ = 1;

        for (n = 0; n < sizeof(lengths) / sizeof(lengths[0]) - 1; n++) {
            sha512(a, big, lengths[n]);
            sha512(b, big, lengths[n + 1]);
            if (memcmp(a, b, sizeof(a)) == 0) {
                all_differ = 0;
            }
        }
        expect("SHA-512 distinguishes lengths across block boundaries",
               all_differ);
    }
}

/* ---------------------------------------------------------------------- */

static void test_curve_constants(void)
{
    uint8_t buf[32];
    char hex[65];

    /* The base point is derived in ed25519.c from y = 4/5 with even x, not
     * transcribed. If the field arithmetic or the decoder is wrong, this is
     * not the canonical encoding. */
    expect("base point derives", ed25519_test_base_point(buf) == 0);
    to_hex(hex, buf, 32);
    expect("base point is the canonical Ed25519 B",
           strcmp(hex, "58666666666666666666666666666666"
                       "66666666666666666666666666666666") == 0);

    /* d = -121665/121666, likewise computed rather than pasted. */
    expect("curve d derives", ed25519_test_curve_d(buf) == 0);
    to_hex(hex, buf, 32);
    expect("curve d is the Ed25519 d",
           strcmp(hex, "a3785913ca4deb75abd841414d0a7000"
                       "98e879777940c78c73fe6f2bee6c0352") == 0);

    /* This is what validates the hardcoded group order: L is by definition
     * the order of B, so [L]B is the identity. Any other literal fails. */
    expect("[L]B is the identity (validates the group-order constant)",
           ed25519_test_group_order_kills_base() == 0);
}

/* ---------------------------------------------------------------------- */

struct vector {
    const char *name;
    const char *public_key;
    const char *message;
    const char *signature;
};

/* RFC 8032 section 7.1, then three generated by OpenSSL 3.0.13. */
static const struct vector valid_vectors[] = {
    { "RFC 8032 test 1 (empty message)",
      "d75a980182b10ab7d54bfed3c964073a0ee172f3daa62325af021a68f707511a",
      "",
      "e5564300c360ac729086e2cc806e828a84877f1eb8e5d974d873e0652249015"
      "55fb8821590a33bacc61e39701cf9b46bd25bf5f0595bbe24655141438e7a100b" },
    { "RFC 8032 test 2 (1 byte)",
      "3d4017c3e843895a92b70aa74d1b7ebc9c982ccf2ec4968cc0cd55f12af4660c",
      "72",
      "92a009a9f0d4cab8720e820b5f642540a2b27b5416503f8fb3762223ebdb69da"
      "085ac1e43e15996e458f3613d0f11d8c387b2eaeb4302aeeb00d291612bb0c00" },
    { "RFC 8032 test 3 (2 bytes)",
      "fc51cd8e6218a1a38da47ed00230f0580816ed13ba3303ac5deb911548908025",
      "af82",
      "6291d657deec24024827e69c3abe01a30ce548a284743a445e3680d7db5ac3ac"
      "18ff9b538d16f290ae67f760984dc6594a7c15e9716ed28dc027beceea1ec40a" },
    { "OpenSSL 3.0.13 vector A",
      "0492701ee36f4bbd210147a484644eb153d9ee1044ef7afff1d940e4121f94ca",
      "354cd98e4909bd",
      "70e2dcdb1fdd01dbbd3599864392a5cc9bd4db23be928a5676cd8954d5533a48"
      "e5f82bf73abc3682f8650ba03199fee6a3316f5b9c863d0e4357f48ce5cecb08" },
    { "OpenSSL 3.0.13 vector B",
      "8204daeec55d5b41f5c42a0af5a8f75aa32701d6c123b56109204f6b4ab331a0",
      "78daadc9313762983073ee0ef541",
      "dad417430a4e178da4556798e001abb2e3c46630e855bc1bf2ac70dcdc3177a7"
      "6a5d5429aa29d737cb8f1a9f80a30d8e6a41500da2c6da9b69e82b7788807b0c" },
    { "OpenSSL 3.0.13 vector C",
      "807f21786f52aff156b21f342edec946775cc5ed54f4fef86734185f8e98985f",
      "216767e159084574eace220f40faef044cee643c6e",
      "ce7ca4fe060f8ba6f16513b2669752c6e5fd5ceae26c49a23b0df88c049ab38b"
      "d72a51757162cfd3d96800a9fec9826e582bb6f5e9c2949a0d4074a0b04ab00f" },
};

static void test_valid_signatures(void)
{
    unsigned n;

    for (n = 0; n < sizeof(valid_vectors) / sizeof(valid_vectors[0]); n++) {
        const struct vector *v = &valid_vectors[n];
        uint8_t pk[32], sig[64], msg[64];
        size_t msg_len;

        unhex(v->public_key, pk, sizeof(pk));
        unhex(v->signature, sig, sizeof(sig));
        msg_len = unhex(v->message, msg, sizeof(msg));

        expect(v->name, ed25519_verify(sig, msg, msg_len, pk) == 0);
    }
}

static void test_rejections(void)
{
    /* Work from a known-good vector and break one thing at a time. */
    const struct vector *v = &valid_vectors[3];
    uint8_t pk[32], sig[64], msg[64];
    size_t msg_len;

    unhex(v->public_key, pk, sizeof(pk));
    unhex(v->signature, sig, sizeof(sig));
    msg_len = unhex(v->message, msg, sizeof(msg));

    {
        uint8_t bad[64];
        memcpy(bad, sig, sizeof(bad));
        bad[0] ^= 0x01;
        expect("flipped bit in R rejected",
               ed25519_verify(bad, msg, msg_len, pk) != 0);
    }

    {
        uint8_t bad[64];
        memcpy(bad, sig, sizeof(bad));
        bad[32] ^= 0x01;
        expect("flipped bit in S rejected",
               ed25519_verify(bad, msg, msg_len, pk) != 0);
    }

    {
        uint8_t bad[64];
        memcpy(bad, msg, msg_len);
        bad[0] ^= 0x01;
        expect("flipped bit in the message rejected",
               ed25519_verify(sig, bad, msg_len, pk) != 0);
    }

    {
        uint8_t bad[32];
        memcpy(bad, pk, sizeof(bad));
        bad[0] ^= 0x01;
        expect("wrong public key rejected",
               ed25519_verify(sig, msg, msg_len, bad) != 0);
    }

    expect("truncated message rejected",
           msg_len == 0 || ed25519_verify(sig, msg, msg_len - 1, pk) != 0);

    /* A signature from a different key over a different message. */
    {
        uint8_t other_pk[32], other_sig[64];
        unhex(valid_vectors[4].public_key, other_pk, sizeof(other_pk));
        unhex(valid_vectors[4].signature, other_sig, sizeof(other_sig));
        expect("signature from another key rejected",
               ed25519_verify(other_sig, msg, msg_len, pk) != 0);
    }

    /* All zeroes. This is the specific input the old placeholder accepted,
     * and the one a caller supplies when it has nothing at all. */
    {
        uint8_t zpk[32], zsig[64], zmsg[32];
        memset(zpk, 0, sizeof(zpk));
        memset(zsig, 0, sizeof(zsig));
        memset(zmsg, 0, sizeof(zmsg));
        expect("all-zero signature and key rejected",
               ed25519_verify(zsig, zmsg, sizeof(zmsg), zpk) != 0);
    }

    expect("NULL signature rejected",
           ed25519_verify(NULL, msg, msg_len, pk) != 0);
    expect("NULL public key rejected",
           ed25519_verify(sig, msg, msg_len, NULL) != 0);
}

static void test_malleability(void)
{
    /* S + L verifies under the same equation as S, because the scalar only
     * matters modulo L. Accepting it means one signed message has many valid
     * signatures — which breaks any caller that treats a signature as a
     * unique identifier, and is what RFC 8032 section 8.4 requires rejecting.
     * The check is S < L, so add L to S and confirm the result is refused. */
    const struct vector *v = &valid_vectors[3];
    uint8_t pk[32], sig[64], msg[64], mauled[64];
    size_t msg_len;
    static const uint8_t L[32] = {
        0xed, 0xd3, 0xf5, 0x5c, 0x1a, 0x63, 0x12, 0x58,
        0xd6, 0x9c, 0xf7, 0xa2, 0xde, 0xf9, 0xde, 0x14,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x10
    };
    unsigned int carry = 0;
    int i;

    unhex(v->public_key, pk, sizeof(pk));
    unhex(v->signature, sig, sizeof(sig));
    msg_len = unhex(v->message, msg, sizeof(msg));

    memcpy(mauled, sig, sizeof(mauled));
    for (i = 0; i < 32; i++) {
        unsigned int cur = (unsigned int)mauled[32 + i] + L[i] + carry;
        mauled[32 + i] = (uint8_t)cur;
        carry = cur >> 8;
    }

    expect("S + L rejected (signature malleability)",
           ed25519_verify(mauled, msg, msg_len, pk) != 0);

    /* Sanity: the unmodified signature still verifies, so the check above is
     * rejecting the mauling rather than something incidental. */
    expect("original signature still verifies",
           ed25519_verify(sig, msg, msg_len, pk) == 0);
}

static void test_scalarmult(void)
{
    uint8_t scalar[32];
    uint8_t out[32], base[32];

    /* [1]B == B, and [0]B is the identity, whose encoding is y=1. */
    memset(scalar, 0, sizeof(scalar));
    scalar[0] = 1;
    expect("scalarmult runs", ed25519_test_scalarmult_base(out, scalar) == 0);
    ed25519_test_base_point(base);
    expect("[1]B == B", memcmp(out, base, 32) == 0);

    memset(scalar, 0, sizeof(scalar));
    ed25519_test_scalarmult_base(out, scalar);
    {
        uint8_t identity[32];
        memset(identity, 0, sizeof(identity));
        identity[0] = 1;
        expect("[0]B is the identity", memcmp(out, identity, 32) == 0);
    }
}

int main(void)
{
    printf("Ed25519 and SHA-512 tests\n");

    test_sha512();
    test_curve_constants();
    test_valid_signatures();
    test_rejections();
    test_malleability();
    test_scalarmult();

    printf("\n%d checks, %d failures\n", checks, failures);
    return failures == 0 ? 0 : 1;
}
