name: Mandalorian CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config: [Debug, Release]
    steps:
    - uses: actions/checkout@v4
    - name: Install deps
      run: |
        sudo apt update
        sudo apt install -y cmake ninja-build pkg-config libsodium-dev gcc-riscv64-unknown-elf
    - name: Configure
      run: mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=${{ matrix.config }} -GNinja
    - name: Build
      run: cd build && ninja -j2
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4
    - name: Install deps
      run: sudo apt install -y libsodium-dev cmake ninja-build
    - name: Build & Test
      run: |
        mkdir tests/build && cd tests/build
        cmake .. -GNinja
        ninja && ctest -V --output-on-failure
  fuzz:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Fuzz
      run: cd tests/fuzz && gcc fuzz_vault.c -o fuzz_vault -l fuzzing -fsanitize=fuzzer

